# Placeholder — replace with the real hardware-configuration.nix generated by
# `nixos-generate-config` on the target machine before deploying.
{
  boot.initrd.availableKernelModules = [ ];
  boot.kernelModules = [ ];
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
}
